- hosts: prod
  user: ec2-user
  gather_facts: ture
  tasks:
   - name: Copy file with owner and permissions
     copy: 
      src: /home/ec2-user/.jenkins/workspace/test-test/sample.war
      dest: /home/ec2-user/tomcat/webapps/
      owner: ec2-user
      group: ec2-user
      mode: '0755'
   - name: Copy file with owner and permissions
     copy:
      src: /home/ec2-user/.jenkins/workspace/test-test/sample.war
      dest: /home/ec2-user/tomcat/work/
      owner: ec2-user
      group: ec2-user
      mode: '0755'
